### ISSUE TITLE
Role is throwing errors on consecutive runs

### ISSUE THREAD

**Issue by zen** [mdsketch/ansible-teleport#1]
AWS Linux 2.

Works fine on first run. Throwing error on next:
```
fatal: [host]: FAILED! => {"changed": true, "cmd": "teleport version\n", "delta": "0:00:00.008927", "end": "2022-03-22 22:34:09.330311", "msg": "non-zero return code", "rc": 127, "start": "2022-03-22 22:34:09.321384", "stderr": "/bin/sh: teleport: command not found", "stderr_lines": ["/bin/sh: teleport: command not found"], "stdout": "", "stdout_lines": []}
```

This is due to `teleport` not being in default PATH.

**Comment by mdsketch** [comment]
I guess I could add a variable for teleport's path, something like "teleport_path". Role is only for debian right now, so default would be easy.

There is probably also a way to lookup where it's installed, use that first if the user hasn't defined a path, then use an OS default.

I'll take a look at this, don't use awx Linux so I won't be able to test the change though.

**Comment by zen** [comment]
Just FYI this will affect any RH derivatives, not only AWS Linux. Role works just fine on RH style systems apart from that (since it is using downloaded binary). I already fixed that, will try to make a PR

**Comment by mdsketch** [comment]
Hey so I took a look at your edits to this role (on your fork), I don't want this to move to installing from package repos because the whole reason I started it was to allow this role to specifically handle the version of teleport installed. I have had some issues with apt updating the installed teleport version (just via me doing apt update) and then I'll have a node on a newer version than my cluster, basically a bad time.

As well there's no arm repo for teleport, and I need the arm compatibility. 

If you were interested I might consider merging the RH part of your edit (just for the ability to install on more systems) but otherwise its gonna have to stay the way it is. 

Glad I could at least offer you a role you could jump off from to make something that works for you.
